@studentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWFlMDU4MTAxY2Q5MDcyYzg0ZTIyMyIsImlhdCI6MTczNDM1MTU1OSwiZXhwIjoxNzM0NDM3OTU5fQ.THu-jPQiisXDmrklfwUW6squl7lFUa3Any_IxvOwVC8
@teacherToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWRiYzM1ODU5ZWJlNTNiODk5MGFiZCIsImlhdCI6MTczNDE5NjI4NiwiZXhwIjoxNzM0MjgyNjg2fQ.TqlzefYedzyWdRk36LFSVulvOPKxXc6OpSVG4wmQIzc

@url=http://localhost:4000/api

### ? API
GET {{url}}

### ? AUTH / REGISTER
POST {{url}}/auth/register
Content-Type: application/json

{
    "name": "Sukhbir Singh",
    "email": "sukhbirsinghsareenxa33@gmail.com",
    "phone": "+923059119149",
    "role": "teacher",
    "password": "1234",
    "stream": "Sciences",
    "subjects": ["Physics", "Chemistry","Biology"]
}

### ? AUTH / REGISTER
POST {{url}}/auth/register
Content-Type: application/json

{
    "name": "Moeez Ali",
    "email": "moeezali2375@test2.com",
    "phone": "+923059119149",
    "role": "student",
    "password": "1234",
    "stream": "Sciences",
    "subjects": ["JEE", "NEET"]
}

### ? AUTH / TOKEN / VERIFY
GET {{url}}/auth/token/verify/879564
Authorization: Bearer {{teacherToken}}

### ? AUTH / TOKEN / REGENERATE
GET {{url}}/auth/token/regenerate
Authorization: Bearer {{studentToken}}

### ? AUTH / LOGIN
POST {{url}}/auth/login
Content-Type: application/json

{
    "email":"moeezali2375@icloud.com",
    "password":"1234"
}

### ? AUTH / PASSWORD
PUT {{url}}/auth/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "oldPassword": "1234",
    "newPassword": "1234"
}

### ? AUTH / EMAIL
PUT {{url}}/auth/email
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "newEmail": "l211798@lhr.nu.edu.pk",
    "password": "1234"
}

### ? AUTH / EMAIL / VERIFY
GET {{url}}/auth/email/verify/774536
Authorization: Bearer {{token}}

### ? AUTH / PWD / FORGET
PUT {{url}}/auth/password/forget
Content-Type: application/json

{
    "email":"moeezali2375@gmail.com"
}

### ? AUTH / PWD / VERIFY / :EMAIL / :TOKEN
PUT {{url}}/auth/password/verify/moeezali2375@gmail.com/7db9d9f7f689a705d3291d78982e41d777bc43201cdc3931686441b7e9b3efd6a13ea3dd6e2ef145270f7e49371e3279c2271494a5b2fc3e817765587c685016
Content-Type: application/json

{
    "password": "12345"
}

### ? PROTECT
GET {{url}}/protect
Authorization: Bearer {{studentToken}}

### ? TEACHER
GET {{url}}/teacher
Authorization: Bearer {{teacherToken}}

### ? TEACHER / TEST
POST {{url}}/teacher/test
Authorization: Bearer {{teacherToken}}
Content-Type: application/json

{
    "name": "JEE Test",
    "description": "This is test-TEST",
    "price": 10,
    "questions": [
        {
            "title": "This is 1st question.",
            "options": ["1st option", "2nd option", "3rd option", "4th option"],
            "solution": 2
        },
        {
            "title": "This is 2nd question.",
            "options": ["1st option", "2nd option", "3rd option", "4th option"],
            "solution": 3
        }
    ]
}

### ? TEACHER / TEST / :ID
PUT {{url}}/teacher/test/675aeda86291a4386f856b56
Authorization: Bearer {{teacherToken}}
Content-Type: application/json

{
    "name": "JEE Test Updated",
    "description": "This is test-TEST",
    "price": 10,
    "questions": [
        {
            "title": "This is 1st question.",
            "options": ["1st option", "2nd option", "3rd option", "4th option"],
            "solution": 2
        },
        {
            "title": "This is 2nd question.",
            "options": ["1st option", "2nd option", "3rd option", "4th option"],
            "solution": 3
        }
    ]
}

### ? TEACHER / TEST
GET {{url}}/teacher/test
Authorization: Bearer {{teacherToken}}


### ? STUDENT / TEST
GET {{url}}/student/test
Authorization: Bearer {{studentToken}}

### ? STUDENT / TEST / TESTID
POST {{url}}/student/test/675aeda86291a4386f856b56
Authorization: Bearer {{studentToken}}

### ? STUDENT / TEST / PENDING
GET {{url}}/student/test/pending
Authorization: Bearer {{studentToken}}

### ? STUDENT / TEST / BOUGHT
GET {{url}}/student/test/query?paid=0
Authorization: Bearer {{studentToken}}

